### ISSUE TITLE
[Bug] wrong link

### ISSUE THREAD

**Issue by 0subzero** [MeteorClientPlus/MeteorPlus#11]
### Describe the bug

check your URL in the info page:

Download [meteor plus](https://github.com/Nekiplay/MeteorPlus/releases) for your version of minecraft

### Steps to reproduce

```bash
-
```

### Meteor Plus Version

-

### Minecraft Version

-

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
?

**Comment by Nekiplay** [comment]
fixed
