### ISSUE TITLE
[Suggestion] enemy 

### ISSUE THREAD

**Issue by pizzav-xyz** [MeteorClientPlus/MeteorPlus#8]
### Description

instead of blacklisting people to not attack(friends) whitelist people to attack 

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
No Interact has it

**Comment by pizzav-xyz** [comment]
? You assigned it to yourself and closed it?

**Comment by Nekiplay** [comment]
The issue has been resolved, so the problem is closed
